---
services:
  publisher:
    build:
      context: ../
      dockerfile: demo/Dockerfile.publisher
    environment:
      DOMAIN: publisher.${DOMAIN}
      SECRET_KEY: ${TRACTION_API_KEY}
      ENDORSER_MULTIKEY: ${ENDORSER_MULTIKEY}
      TRACTION_API_URL: ${TRACTION_API_URL}
      TRACTION_API_KEY: ${TRACTION_API_KEY}
      TRACTION_TENANT_ID: ${TRACTION_TENANT_ID}
      ORGBOOK_URL: ${ORGBOOK_URL}
      ORGBOOK_API_URL: ${ORGBOOK_API_URL}
      ORGBOOK_VC_SERVICE: 'http://resolver.${DOMAIN}'
      DID_WEB_SERVER_URL: ${DID_WEB_SERVER_URL}
      AGENT_ADMIN_URL: 'http://agent:8020'
      AGENT_ADMIN_API_KEY: ${TRACTION_API_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.publisher.rule=Host(`publisher.${DOMAIN}`)
      - traefik.http.routers.publisher.entrypoints=web
      - traefik.http.services.publisher.loadbalancer.server.port=8000

  resolver:
    build:
      context: ../
      dockerfile: demo/Dockerfile.resolver
    environment:
      DOMAIN: resolver.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.resolver.rule=Host(`resolver.${DOMAIN}`)
      - traefik.http.routers.resolver.entrypoints=web
      - traefik.http.services.resolver.loadbalancer.server.port=8000

  frontend:
    build:
      context: ../
      dockerfile: demo/Dockerfile.frontend
    environment:
      DOMAIN: ui.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`ui.${DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.services.frontend.loadbalancer.server.port=5000

  # issuer:
  #   build:
  #     context: https://github.com/OpSecId/aries-cloudagent-python.git#pstlouis/add-did-web-register-route
  #     dockerfile: docker/Dockerfile
  #   entrypoint: ["aca-py", "start"]
  #   command: [
  #     '--no-ledger',
  #     '--no-transport',
  #     '--admin', '0.0.0.0', '8020',
  #     '--admin-insecure',
  #     '--wallet-allow-insecure-seed',
  #   ]
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.issuer.rule=Host(`issuer.${DOMAIN}`)
  #     - traefik.http.routers.issuer.entrypoints=web
  #     - traefik.http.services.issuer.loadbalancer.server.port=8020

  # provision:
  #   image: curlimages/curl
  #   entrypoint: ["/bin/sh","-c"]
  #   command:
  #     - |
  #       curl --retry 5 --retry-connrefused \
  #         -X 'POST' 'http://endorser:8020/wallet/did/create' \
  #         -d '{"method": "web", "seed": "${ENDORSER_SEED}", "options": {"key_type": "ed25519", "did": "did:web:server.${DOMAIN}"}}'

  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro